name: task_manager_app
description: Flutter Task Manager Mobile App

publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  date_picker_timeline: ^1.2.1
  flutter_local_notifications: ^17.2.4
  flutter_staggered_animations: ^1.1.0
  flutter_svg: ^2.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  sqflite: ^2.3.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  image_path: "images/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  
  assets:
    - images/
